config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :users
  resources :items
  resources :orders
  resource :confirmation, :only => [:show]
  resource :user_sessions, :only => [:create, :new, :destroy]
  root 'home#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :product_id, presence: true
  validates :order_id, presence: true
  validates :quantity, numericality: true

  def increase_quantity(quantity)
  	self.quantity += quantity.to_i
  end

  def unity_price
  	self.product.price
  end

  def name
  	self.product.name
  end

  def total_price
  	self.product.price * self.quantity
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :set_product, only: [:create]
	before_action :set_quantity, only: [:create]
  before_action :set_item, only: [:destroy]

  def index
    @items = current_order.items
  end

	def create
    current_order.save
    session[:order_id] = current_order.id

    current_order.add_product_and_quantity(@product, @quantity)

    respond_to do |format|
      format.html { redirect_to items_path, notice: 'Product was successfully created.' }
    end
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.js { head :ok }
    end
  end

  private

  	def set_product
			@product = Product.find(params[:id])
  	end

  	def set_quantity
			@quantity = params[:quantity]
  	end

    def set_item
      @item = Item.find_by_product_id(params[:id])
    end

end

app/views/items/index.html.erb
<h2>Shopping Cart</h2>


<% if @items.any? %>
<div class="container" id="cart">
  <div class="row">
    <div class="col-sm-12 col-md-10 col-md-offset-1">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th class="text-center">Price</th>
            <th class="text-center">Total</th>
            <th> </th>
          </tr>
        </thead>
        <tbody>
        <% @items.each do |item| %>
          <tr id="_<%= item.id %>" class="item">
            <td class="col-sm-8 col-md-6">
              <div class="media">
              	<%= link_to products_path, :class => "pull-left" do %>
                	<%= image_tag(item.product.picture.thumb.url, size: "100x100") %> 
                <% end %>
                <div class="media-body">
                    <h4 class="media-heading"><%= item.name %></h4>
                    <span>Status: </span>
                    <span class="text-success"><strong>In Stock</strong></span>
                </div>
              </div>
            </td>
            <td class="col-sm-1 col-md-1" style="text-align: center">
            	<%= text_field_tag :quantity, item.quantity, class: "form-control", 
              id: "quantity_#{item.id}" %>
            </td>
            <td class="col-sm-1 col-md-1 text-center">
            	<strong><%= item.unity_price %></strong>
            </td>
            <td class="col-sm-1 col-md-1 text-center">
            	<strong id="total_<%= item.id %>"><%= item.total_price %></strong>
            </td>
            <td class="col-sm-1 col-md-1">
              <%= link_to 'Remove', item_path(item.product.id), method: :delete, 
							remote: true, id: "remove_item_#{item.id}", class: "btn btn-danger remover" %>
            </td>
          </tr>
          <script>
					  $('#remove_item_<%= item.id %>').bind('ajax:success', function(){
					    
              $('#_<%= item.id %>').remove();
					    $('#_menu_<%= item.id %>').remove();

              var cart = new Cart($("#cart"));
              if(cart.isEmpty())
                cart.clear();
              else
                cart.update();
					  });
					</script>
          <% end %>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td><h5>Subtotal</h5></td>
            <td class="text-right">
            	<h5><strong><%= current_order.total_price %></strong></h5>
            </td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td><h5>Estimated shipping</h5></td>
            <td class="text-right"><h5><strong>$6.94</strong></h5></td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td ><h3>Total</h3></td>
            <td class="text-right">
            	<h3><strong id="cart_total"><%= current_order.total_price %></strong></h3>
            </td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>
	            <%= link_to products_path, :class => "btn btn-default" do %>
							  <span class="glyphicon glyphicon-shopping-cart"></span> Continue Shopping
							<% end %>
            </td>
            <td>
            	<%= link_to 'Check out', orders_path , class: "btn btn-success pull-right"%>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<% else %>
	<h1>Emptity Cart</h1>
<% end %>