config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :users
  resources :items
  resources :orders
  resource :confirmation, :only => [:show]
  resource :user_sessions, :only => [:create, :new, :destroy]
  root 'home#index'

end

app/views/layouts/_menu_login.html.erb
<ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <b>Login</b> 
        <span class="caret"></span>
      </a>
    <ul id="login-dp" class="dropdown-menu">
      <li>
         <div class="row">
            <div class="col-md-12">
              Login 
              <%= form_tag(user_sessions_path, :method => :post, remote: true) do %> 
                <p> 
                  <%= text_field_tag "user_session[email]", nil, class: 'form-control', placeholder: 'Email address' %> 
                </p> 
                <p> 
                  <%= password_field_tag "user_session[password]", nil, class: 'form-control', placeholder: 'Password' %> 
                </p> 
                <div class="help-block text-right">
                  <a href="">Forget the password ?</a>
                </div>
                <p> 
                  <%= submit_tag "Sign in", class: "btn btn-primary btn-block" %> 
                </p>
                <div class="checkbox">
                   <label>
                   <input type="checkbox"> keep me logged-in
                   </label>
                </div>
              <% end %>  
            </div>
            <div class="bottom text-center">
              New here ? 
              <b><%= link_to("Join Us", new_user_path) %></b>
            </div>
         </div>
      </li>
    </ul>
  </li>
</ul>

 <script>
  $('form').bind('ajax:complete', function(xhr, result){
    console.log(result);
    if(result.status == 200){
      $('#login_logout').replaceWith(result.responseText);
      $.notify("Authenticated user!", "success");
    }
  });
 </script>

app/views/layouts/_menu_logout.html.erb
<ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
     <%= link_to "Logout", user_sessions_path, :method => :delete %>
  </li>
</ul>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand div_image" href="#"></a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- area de login -->
      <div id="login_logout" >
        <% if user_signed_in? %> 
          <%= render 'layouts/menu_logout' %> 
        <% else %> 
          <%= render 'layouts/menu_login' %> 
        <% end %>
      </div>

      <!-- area do carrinho -->
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
            <span class="glyphicon glyphicon-shopping-cart"></span> 
            <span id="cart_quantity"><%= current_order.quantity_items %></span> - Item(s)
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu dropdown-cart" role="menu">
              <li>
                <% if current_order.no_empty? %>
                  <% current_order.items.each do |item| %>
                    <span class="item" id="_menu_<%= item.id %>">
                      <span class="item-left">
                          <%= image_tag(item.product.picture.thumb.url, size: "50x50") %>
                          <span class="item-info">
                              <span><%= truncate(item.name, length: 20) %></span>
                              <span><%= item.unity_price %></span>
                          </span>
                      </span>
                    </span>
                  <% end %>
                <% else %>
                  <a class="text-center" href="">Empty Cart</a>
                <% end %>
              </li>
              <li class="divider"></li>
              <li><%= link_to 'View Cart', items_path , class: "text-center" %></li>
          </ul>
        </li>
      </ul>

      <!-- area de pesquisa -->
      <form class="navbar-form navbar-right" role="search">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Pesquisar" id="search">
          <div class="input-group-btn">
              <button class="btn btn-default" type="submit">
                <i class="glyphicon glyphicon-search"></i>
              </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="col-md-3">
  <div class="list-group">
    <%= link_to('Category', '', class: "list-group-item active") %>
    <% categories.each do |category| %>
      <%= link_to(category.description, products_path, class: "list-group-item") %>
    <% end %>
  </div>
  <div>
      <a href="#" class="list-group-item active ">Size</a>
      <ul class="nav nav-squared list-group">
        <li class="">
          <a href="#" rel="follow" title="PP">
          <span>PP</span>
          </a>
        </li>
        <li class="">
          <a href="#" rel="follow" title="P">
          <span>P</span>
          </a>
        </li>
        <li class="">
          <a href="#" rel="follow" title="P/M">
          <span>P/M</span>
          </a>
        </li>
        <li class="">
          <a href="#" rel="follow" title="M">
          <span>M</span>
          </a>
        </li>
        <li class="">
          <a href="#" rel="follow" title="M/G">
          <span>M/G</span>
          </a>
        </li>
        <li class="">
          <a href="#" rel="follow" title="G">
          <span>G</span>
          </a>
        </li>
        <li class="">
          <a href="#" rel="follow" title="GG">
          <span>GG</span>
          </a>
        </li>
        <li class="">
          <a href="#" rel="follow" title="GGG">
          <span>GGG</span>
          </a>
        </li>
      </ul>

  </div>
  <div class="list-group">
    <%= link_to('Price', '', class: "list-group-item active") %>
    <% precos.each do |preco| %>
      <%= link_to(preco[1], products_path, class: "list-group-item") %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kamisetas</title>
    <meta charset="utf-8">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <script>
    <%= yield :js %>
  </script>
  <body>

    <!--menu superior -->
    <%= render 'layouts/navbar' %>

    <div class="container">
      <div class="row">
        <!--menu lateral -->
        <% if display_sidebar? %>
          <%= render 'layouts/sidebar' %>
        <% end %> 

        <!--conteúdo -->
        <div class=<%= div_content_size %> >
          <%= yield %>
        </div>

      </div>
    </div>

    <!--Footer -->
   
    <div class="col-md-12 end-box ">
        &copy; 2014 | &nbsp; All Rights Reserved | &nbsp; Your Company Name
    </div>

  </body>
</html>